config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get 'test_pages/home'

  get 'test_pages/profile_a'

  get 'test_pages/profile_b'

  root 'test_pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/test_pages_controller.rb
class TestPagesController < ApplicationController
  def home
  end

  def profile_a
  end

  def profile_b
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_pages_helper.rb
module TestPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMAProfiles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <p><br/><br/></p>
      <p><br/><br/></p>

      <% if notice %>
	  <div class="alert alert-success"><%= notice %></div>
      <% end %>
      
      <% if alert %>
	  <div class="alert alert-warning"><%= alert %></div>
      <% end %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navy">
    <div class="container">
      <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	  <span class="sr-only">Toggle navigation</span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	</button>
	<%= link_to "ANDERSON'S DEMO", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
	  <li><%= link_to "Home", root_path, class: "active"  %></li>
	  <li><%= link_to "Home", root_path, class: "active"  %></li>
	  <li><%=link_to "Home",  root_path, class: "active" %></li>
	  <li><%=link_to "Home",  root_path, class: "active"  %></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	    <li><%= link_to current_user.email, edit_user_registration_path %></li>
	    <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
	<% elsif admin_signed_in? %>
	    <li><%= link_to current_admin.email, edit_admin_registration_path %></li>
	    <li><%= link_to "SIGN OUT", destroy_admin_session_path, method: :delete %></li>
	<% else %>
	    <li><%= link_to "SIGN IN", new_user_session_path %></li>
	    <li> &nbsp; &nbsp;</li>
	    <li><%= link_to "REGISTER", new_user_registration_path %></li>
	<% end %>
	</ul>
      </div>
    </div>
  </div>
</nav>

app/views/test_pages/home.html.erb
<h1>Devise Heirarchy Tester</h1>
<p>When user properly logged in, button below reads "ACTIVE"</p>
<% if user_signed_in? %>
<p><%= link_to "USER ACCESS", root_path, class: "btn btn-lg btn-primary" %></p>
  <% elsif admin_signed_in? %>
<p><%= link_to "ADMIN ACCESS", root_path, class: "btn btn-lg btn-success" %></p>
<% else %>
<p><%= link_to "NO ACCESS", root_path, class: "btn btn-lg btn-danger" %></p>
<% end %>

app/views/test_pages/profile_a.html.erb
<h1>TestPages#profile_a</h1>
<p>Find me in app/views/test_pages/profile_a.html.erb</p>

app/views/test_pages/profile_b.html.erb
<h1>TestPages#profile_b</h1>
<p>Find me in app/views/test_pages/profile_b.html.erb</p>